/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetTheTeamRouteImport } from './routes/meet-the-team'
import { Route as MotorsportRouteImport } from './routes/motorsport'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as TradeSolutionsRouteImport } from './routes/trade-solutions'
import { Route as WhyAutomotiveBrandsRouteImport } from './routes/why-automotive-brands'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCostIntelligenceRouteImport } from './routes/admin.cost-intelligence'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminVersionUpdatesRouteImport } from './routes/admin.version-updates'
import { Route as ApiBuildRouteImport } from './routes/api/build'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmActivitiesRouteImport } from './routes/crm.activities'
import { Route as CrmApplicationsRouteImport } from './routes/crm.applications'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmManagerRouteImport } from './routes/crm.manager'
import { Route as CrmOverviewRouteImport } from './routes/crm.overview'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalBasketRouteImport } from './routes/portal.basket'
import { Route as PortalCheckoutRouteImport } from './routes/portal.checkout'
import { Route as PortalFavouritesRouteImport } from './routes/portal.favourites'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalPurchasesRouteImport } from './routes/portal.purchases'
import { Route as PortalQuickOrderRouteImport } from './routes/portal.quick-order'
import { Route as PortalQuotesRouteImport } from './routes/portal.quotes'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalUsersRouteImport } from './routes/portal.users'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSkuRouteImport } from './routes/products.$sku'
import { Route as PurchasingIndexRouteImport } from './routes/purchasing.index'
import { Route as PurchasingForecastRouteImport } from './routes/purchasing.forecast'
import { Route as PurchasingOverstockRouteImport } from './routes/purchasing.overstock'
import { Route as PurchasingPlannerRouteImport } from './routes/purchasing.planner'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesSalesIntelligenceRouteImport } from './routes/sales.sales-intelligence'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin.applications.index'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminContentSlugRouteImport } from './routes/admin.content.$slug'
import { Route as AdminContentMediaRouteImport } from './routes/admin.content.media'
import { Route as AdminContentTeamRouteImport } from './routes/admin.content.team'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminCustomersAutopartAccountsRouteImport } from './routes/admin.customers.autopart-accounts'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminPricingIndexRouteImport } from './routes/admin.pricing.index'
import { Route as AdminPricingIdRouteImport } from './routes/admin.pricing.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminProductsDocumentsRouteImport } from './routes/admin.products.documents'
import { Route as AdminProductsDocumentsImportRouteImport } from './routes/admin.products.documents-import'
import { Route as AdminProductsImportsRouteImport } from './routes/admin.products.imports'
import { Route as AdminProductsStockRouteImport } from './routes/admin.products.stock'
import { Route as AdminSecurityMfaRouteImport } from './routes/admin.security.mfa'
import { Route as AdminVersionUpdatesIndexRouteImport } from './routes/admin.version-updates.index'
import { Route as AdminVersionUpdatesIdRouteImport } from './routes/admin.version-updates.$id'
import { Route as AdminVersionUpdatesNewRouteImport } from './routes/admin.version-updates.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCmsMediaIdRouteImport } from './routes/api/cms-media/$id'
import { Route as ApiInternalStockSyncRouteImport } from './routes/api.internal.stock-sync'
import { Route as ApiProductDocumentsIdRouteImport } from './routes/api/product-documents/$id'
import { Route as PortalOrdersIndexRouteImport } from './routes/portal.orders.index'
import { Route as PortalOrdersOrderIdRouteImport } from './routes/portal.orders.$orderId'
import { Route as PortalQuotesIndexRouteImport } from './routes/portal.quotes.index'
import { Route as PortalQuotesQuoteIdRouteImport } from './routes/portal.quotes.$quoteId'
import { Route as ProductsCategorySlugRouteImport } from './routes/products.category.$slug'
import { Route as PurchasingForecastIndexRouteImport } from './routes/purchasing.forecast.index'
import { Route as PurchasingForecastSkuRouteImport } from './routes/purchasing.forecast.$sku'
import { Route as SalesCustomersIndexRouteImport } from './routes/sales.customers.index'
import { Route as SalesCustomersIdRouteImport } from './routes/sales.customers.$id'
import { Route as SalesQuotesIndexRouteImport } from './routes/sales.quotes.index'
import { Route as SalesQuotesQuoteIdRouteImport } from './routes/sales.quotes.$quoteId'
import { Route as SalesQuotesNewRouteImport } from './routes/sales.quotes.new'
import { Route as SalesSalesIntelligenceIndexRouteImport } from './routes/sales.sales-intelligence.index'
import { Route as SalesSalesIntelligenceDailyBriefRouteImport } from './routes/sales.sales-intelligence.daily-brief'
import { Route as SalesSalesIntelligenceGapsRouteImport } from './routes/sales.sales-intelligence.gaps'
import { Route as SalesSalesIntelligenceOpportunitiesRouteImport } from './routes/sales.sales-intelligence.opportunities'
import { Route as SalesSalesIntelligencePortfolioRouteImport } from './routes/sales.sales-intelligence.portfolio'
import { Route as SalesSalesIntelligenceRebatesRouteImport } from './routes/sales.sales-intelligence.rebates'
import { Route as AdminContentSlugPreviewRouteImport } from './routes/admin.content.$slug.preview'
import { Route as AdminCustomersGroupsIndexRouteImport } from './routes/admin.customers.groups.index'
import { Route as AdminCustomersGroupsGroupIdRouteImport } from './routes/admin.customers.groups.$groupId'
import { Route as AdminProductsImportsIndexRouteImport } from './routes/admin.products.imports.index'
import { Route as AdminProductsImportsIdRouteImport } from './routes/admin.products.imports.$id'
import { Route as PortalOrdersOrderIdIndexRouteImport } from './routes/portal.orders.$orderId.index'
import { Route as PortalOrdersOrderIdConfirmationRouteImport } from './routes/portal.orders.$orderId.confirmation'
import { Route as AdminProductsStockProductSkuRouteImport } from './routes/admin.products.stock.product.$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheTeamRoute = MeetTheTeamRouteImport.update({
  id: '/meet-the-team',
  path: '/meet-the-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorsportRoute = MotorsportRouteImport.update({
  id: '/motorsport',
  path: '/motorsport',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSolutionsRoute = TradeSolutionsRouteImport.update({
  id: '/trade-solutions',
  path: '/trade-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyAutomotiveBrandsRoute = WhyAutomotiveBrandsRouteImport.update({
  id: '/why-automotive-brands',
  path: '/why-automotive-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostIntelligenceRoute = AdminCostIntelligenceRouteImport.update({
  id: '/cost-intelligence',
  path: '/cost-intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVersionUpdatesRoute = AdminVersionUpdatesRouteImport.update({
  id: '/version-updates',
  path: '/version-updates',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBuildRoute = ApiBuildRouteImport.update({
  id: '/api/build',
  path: '/api/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmActivitiesRoute = CrmActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => CrmRoute,
} as any)
const CrmApplicationsRoute = CrmApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmManagerRoute = CrmManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOverviewRoute = CrmOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CrmRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBasketRoute = PortalBasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCheckoutRoute = PortalCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFavouritesRoute = PortalFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPurchasesRoute = PortalPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuickOrderRoute = PortalQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuotesRoute = PortalQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUsersRoute = PortalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSkuRoute = ProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingIndexRoute = PurchasingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasingRoute,
} as any)
const PurchasingForecastRoute = PurchasingForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => PurchasingRoute,
} as any)
const PurchasingOverstockRoute = PurchasingOverstockRouteImport.update({
  id: '/overstock',
  path: '/overstock',
  getParentRoute: () => PurchasingRoute,
} as any)
const PurchasingPlannerRoute = PurchasingPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => PurchasingRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesSalesIntelligenceRoute = SalesSalesIntelligenceRouteImport.update({
  id: '/sales-intelligence',
  path: '/sales-intelligence',
  getParentRoute: () => SalesRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentSlugRoute = AdminContentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentMediaRoute = AdminContentMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentTeamRoute = AdminContentTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersAutopartAccountsRoute =
  AdminCustomersAutopartAccountsRouteImport.update({
    id: '/customers/autopart-accounts',
    path: '/customers/autopart-accounts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminPricingIndexRoute = AdminPricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPricingRoute,
} as any)
const AdminPricingIdRoute = AdminPricingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPricingRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsDocumentsRoute = AdminProductsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsDocumentsImportRoute =
  AdminProductsDocumentsImportRouteImport.update({
    id: '/documents-import',
    path: '/documents-import',
    getParentRoute: () => AdminProductsRoute,
  } as any)
const AdminProductsImportsRoute = AdminProductsImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsStockRoute = AdminProductsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminSecurityMfaRoute = AdminSecurityMfaRouteImport.update({
  id: '/security/mfa',
  path: '/security/mfa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVersionUpdatesIndexRoute =
  AdminVersionUpdatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminVersionUpdatesRoute,
  } as any)
const AdminVersionUpdatesIdRoute = AdminVersionUpdatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVersionUpdatesRoute,
} as any)
const AdminVersionUpdatesNewRoute = AdminVersionUpdatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVersionUpdatesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsMediaIdRoute = ApiCmsMediaIdRouteImport.update({
  id: '/api/cms-media/$id',
  path: '/api/cms-media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalStockSyncRoute = ApiInternalStockSyncRouteImport.update({
  id: '/api/internal/stock-sync',
  path: '/api/internal/stock-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductDocumentsIdRoute = ApiProductDocumentsIdRouteImport.update({
  id: '/api/product-documents/$id',
  path: '/api/product-documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOrdersIndexRoute = PortalOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalOrdersRoute,
} as any)
const PortalOrdersOrderIdRoute = PortalOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => PortalOrdersRoute,
} as any)
const PortalQuotesIndexRoute = PortalQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalQuotesRoute,
} as any)
const PortalQuotesQuoteIdRoute = PortalQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => PortalQuotesRoute,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/products/category/$slug',
  path: '/products/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingForecastIndexRoute = PurchasingForecastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasingForecastRoute,
} as any)
const PurchasingForecastSkuRoute = PurchasingForecastSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => PurchasingForecastRoute,
} as any)
const SalesCustomersIndexRoute = SalesCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesCustomersIdRoute = SalesCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => SalesRoute,
} as any)
const SalesQuotesIndexRoute = SalesQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesQuotesQuoteIdRoute = SalesQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => SalesRoute,
} as any)
const SalesQuotesNewRoute = SalesQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => SalesRoute,
} as any)
const SalesSalesIntelligenceIndexRoute =
  SalesSalesIntelligenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SalesSalesIntelligenceRoute,
  } as any)
const SalesSalesIntelligenceDailyBriefRoute =
  SalesSalesIntelligenceDailyBriefRouteImport.update({
    id: '/daily-brief',
    path: '/daily-brief',
    getParentRoute: () => SalesSalesIntelligenceRoute,
  } as any)
const SalesSalesIntelligenceGapsRoute =
  SalesSalesIntelligenceGapsRouteImport.update({
    id: '/gaps',
    path: '/gaps',
    getParentRoute: () => SalesSalesIntelligenceRoute,
  } as any)
const SalesSalesIntelligenceOpportunitiesRoute =
  SalesSalesIntelligenceOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => SalesSalesIntelligenceRoute,
  } as any)
const SalesSalesIntelligencePortfolioRoute =
  SalesSalesIntelligencePortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => SalesSalesIntelligenceRoute,
  } as any)
const SalesSalesIntelligenceRebatesRoute =
  SalesSalesIntelligenceRebatesRouteImport.update({
    id: '/rebates',
    path: '/rebates',
    getParentRoute: () => SalesSalesIntelligenceRoute,
  } as any)
const AdminContentSlugPreviewRoute = AdminContentSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminContentSlugRoute,
} as any)
const AdminCustomersGroupsIndexRoute =
  AdminCustomersGroupsIndexRouteImport.update({
    id: '/customers/groups/',
    path: '/customers/groups/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersGroupsGroupIdRoute =
  AdminCustomersGroupsGroupIdRouteImport.update({
    id: '/customers/groups/$groupId',
    path: '/customers/groups/$groupId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsImportsIndexRoute =
  AdminProductsImportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProductsImportsRoute,
  } as any)
const AdminProductsImportsIdRoute = AdminProductsImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsImportsRoute,
} as any)
const PortalOrdersOrderIdIndexRoute =
  PortalOrdersOrderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalOrdersOrderIdRoute,
  } as any)
const PortalOrdersOrderIdConfirmationRoute =
  PortalOrdersOrderIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => PortalOrdersOrderIdRoute,
  } as any)
const AdminProductsStockProductSkuRoute =
  AdminProductsStockProductSkuRouteImport.update({
    id: '/product/$sku',
    path: '/product/$sku',
    getParentRoute: () => AdminProductsStockRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/motorsport': typeof MotorsportRoute
  '/portal': typeof PortalRouteWithChildren
  '/purchasing': typeof PurchasingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales': typeof SalesRouteWithChildren
  '/trade-solutions': typeof TradeSolutionsRoute
  '/why-automotive-brands': typeof WhyAutomotiveBrandsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/cost-intelligence': typeof AdminCostIntelligenceRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/version-updates': typeof AdminVersionUpdatesRouteWithChildren
  '/api/build': typeof ApiBuildRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/applications': typeof CrmApplicationsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/manager': typeof CrmManagerRoute
  '/crm/overview': typeof CrmOverviewRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/portal/basket': typeof PortalBasketRoute
  '/portal/checkout': typeof PortalCheckoutRoute
  '/portal/favourites': typeof PortalFavouritesRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRouteWithChildren
  '/portal/purchases': typeof PortalPurchasesRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/quotes': typeof PortalQuotesRouteWithChildren
  '/portal/support': typeof PortalSupportRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/purchasing/forecast': typeof PurchasingForecastRouteWithChildren
  '/purchasing/overstock': typeof PurchasingOverstockRoute
  '/purchasing/planner': typeof PurchasingPlannerRoute
  '/sales/sales-intelligence': typeof SalesSalesIntelligenceRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchasing/': typeof PurchasingIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/admin/content/$slug': typeof AdminContentSlugRouteWithChildren
  '/admin/content/media': typeof AdminContentMediaRoute
  '/admin/content/team': typeof AdminContentTeamRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/autopart-accounts': typeof AdminCustomersAutopartAccountsRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/documents': typeof AdminProductsDocumentsRoute
  '/admin/products/documents-import': typeof AdminProductsDocumentsImportRoute
  '/admin/products/imports': typeof AdminProductsImportsRouteWithChildren
  '/admin/products/stock': typeof AdminProductsStockRouteWithChildren
  '/admin/security/mfa': typeof AdminSecurityMfaRoute
  '/admin/version-updates/$id': typeof AdminVersionUpdatesIdRoute
  '/admin/version-updates/new': typeof AdminVersionUpdatesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cms-media/$id': typeof ApiCmsMediaIdRoute
  '/api/internal/stock-sync': typeof ApiInternalStockSyncRoute
  '/api/product-documents/$id': typeof ApiProductDocumentsIdRoute
  '/portal/orders/$orderId': typeof PortalOrdersOrderIdRouteWithChildren
  '/portal/quotes/$quoteId': typeof PortalQuotesQuoteIdRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
  '/purchasing/forecast/$sku': typeof PurchasingForecastSkuRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/quotes/$quoteId': typeof SalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/sales/sales-intelligence/daily-brief': typeof SalesSalesIntelligenceDailyBriefRoute
  '/sales/sales-intelligence/gaps': typeof SalesSalesIntelligenceGapsRoute
  '/sales/sales-intelligence/opportunities': typeof SalesSalesIntelligenceOpportunitiesRoute
  '/sales/sales-intelligence/portfolio': typeof SalesSalesIntelligencePortfolioRoute
  '/sales/sales-intelligence/rebates': typeof SalesSalesIntelligenceRebatesRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pricing/': typeof AdminPricingIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/version-updates/': typeof AdminVersionUpdatesIndexRoute
  '/portal/orders/': typeof PortalOrdersIndexRoute
  '/portal/quotes/': typeof PortalQuotesIndexRoute
  '/purchasing/forecast/': typeof PurchasingForecastIndexRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/quotes/': typeof SalesQuotesIndexRoute
  '/sales/sales-intelligence/': typeof SalesSalesIntelligenceIndexRoute
  '/admin/content/$slug/preview': typeof AdminContentSlugPreviewRoute
  '/admin/customers/groups/$groupId': typeof AdminCustomersGroupsGroupIdRoute
  '/admin/products/imports/$id': typeof AdminProductsImportsIdRoute
  '/portal/orders/$orderId/confirmation': typeof PortalOrdersOrderIdConfirmationRoute
  '/admin/customers/groups/': typeof AdminCustomersGroupsIndexRoute
  '/admin/products/imports/': typeof AdminProductsImportsIndexRoute
  '/portal/orders/$orderId/': typeof PortalOrdersOrderIdIndexRoute
  '/admin/products/stock/product/$sku': typeof AdminProductsStockProductSkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/motorsport': typeof MotorsportRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/trade-solutions': typeof TradeSolutionsRoute
  '/why-automotive-brands': typeof WhyAutomotiveBrandsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cost-intelligence': typeof AdminCostIntelligenceRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/build': typeof ApiBuildRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/applications': typeof CrmApplicationsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/manager': typeof CrmManagerRoute
  '/crm/overview': typeof CrmOverviewRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/portal/basket': typeof PortalBasketRoute
  '/portal/checkout': typeof PortalCheckoutRoute
  '/portal/favourites': typeof PortalFavouritesRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/purchases': typeof PortalPurchasesRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/purchasing/overstock': typeof PurchasingOverstockRoute
  '/purchasing/planner': typeof PurchasingPlannerRoute
  '/admin': typeof AdminIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/crm': typeof CrmIndexRoute
  '/portal': typeof PortalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchasing': typeof PurchasingIndexRoute
  '/sales': typeof SalesIndexRoute
  '/admin/content/$slug': typeof AdminContentSlugRouteWithChildren
  '/admin/content/media': typeof AdminContentMediaRoute
  '/admin/content/team': typeof AdminContentTeamRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/autopart-accounts': typeof AdminCustomersAutopartAccountsRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/documents': typeof AdminProductsDocumentsRoute
  '/admin/products/documents-import': typeof AdminProductsDocumentsImportRoute
  '/admin/products/stock': typeof AdminProductsStockRouteWithChildren
  '/admin/security/mfa': typeof AdminSecurityMfaRoute
  '/admin/version-updates/$id': typeof AdminVersionUpdatesIdRoute
  '/admin/version-updates/new': typeof AdminVersionUpdatesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cms-media/$id': typeof ApiCmsMediaIdRoute
  '/api/internal/stock-sync': typeof ApiInternalStockSyncRoute
  '/api/product-documents/$id': typeof ApiProductDocumentsIdRoute
  '/portal/quotes/$quoteId': typeof PortalQuotesQuoteIdRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
  '/purchasing/forecast/$sku': typeof PurchasingForecastSkuRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/quotes/$quoteId': typeof SalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/sales/sales-intelligence/daily-brief': typeof SalesSalesIntelligenceDailyBriefRoute
  '/sales/sales-intelligence/gaps': typeof SalesSalesIntelligenceGapsRoute
  '/sales/sales-intelligence/opportunities': typeof SalesSalesIntelligenceOpportunitiesRoute
  '/sales/sales-intelligence/portfolio': typeof SalesSalesIntelligencePortfolioRoute
  '/sales/sales-intelligence/rebates': typeof SalesSalesIntelligenceRebatesRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pricing': typeof AdminPricingIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/version-updates': typeof AdminVersionUpdatesIndexRoute
  '/portal/orders': typeof PortalOrdersIndexRoute
  '/portal/quotes': typeof PortalQuotesIndexRoute
  '/purchasing/forecast': typeof PurchasingForecastIndexRoute
  '/sales/customers': typeof SalesCustomersIndexRoute
  '/sales/quotes': typeof SalesQuotesIndexRoute
  '/sales/sales-intelligence': typeof SalesSalesIntelligenceIndexRoute
  '/admin/content/$slug/preview': typeof AdminContentSlugPreviewRoute
  '/admin/customers/groups/$groupId': typeof AdminCustomersGroupsGroupIdRoute
  '/admin/products/imports/$id': typeof AdminProductsImportsIdRoute
  '/portal/orders/$orderId/confirmation': typeof PortalOrdersOrderIdConfirmationRoute
  '/admin/customers/groups': typeof AdminCustomersGroupsIndexRoute
  '/admin/products/imports': typeof AdminProductsImportsIndexRoute
  '/portal/orders/$orderId': typeof PortalOrdersOrderIdIndexRoute
  '/admin/products/stock/product/$sku': typeof AdminProductsStockProductSkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/motorsport': typeof MotorsportRoute
  '/portal': typeof PortalRouteWithChildren
  '/purchasing': typeof PurchasingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales': typeof SalesRouteWithChildren
  '/trade-solutions': typeof TradeSolutionsRoute
  '/why-automotive-brands': typeof WhyAutomotiveBrandsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/cost-intelligence': typeof AdminCostIntelligenceRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/version-updates': typeof AdminVersionUpdatesRouteWithChildren
  '/api/build': typeof ApiBuildRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/applications': typeof CrmApplicationsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/manager': typeof CrmManagerRoute
  '/crm/overview': typeof CrmOverviewRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/portal/basket': typeof PortalBasketRoute
  '/portal/checkout': typeof PortalCheckoutRoute
  '/portal/favourites': typeof PortalFavouritesRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRouteWithChildren
  '/portal/purchases': typeof PortalPurchasesRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/quotes': typeof PortalQuotesRouteWithChildren
  '/portal/support': typeof PortalSupportRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/purchasing/forecast': typeof PurchasingForecastRouteWithChildren
  '/purchasing/overstock': typeof PurchasingOverstockRoute
  '/purchasing/planner': typeof PurchasingPlannerRoute
  '/sales/sales-intelligence': typeof SalesSalesIntelligenceRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchasing/': typeof PurchasingIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/admin/content/$slug': typeof AdminContentSlugRouteWithChildren
  '/admin/content/media': typeof AdminContentMediaRoute
  '/admin/content/team': typeof AdminContentTeamRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/autopart-accounts': typeof AdminCustomersAutopartAccountsRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/documents': typeof AdminProductsDocumentsRoute
  '/admin/products/documents-import': typeof AdminProductsDocumentsImportRoute
  '/admin/products/imports': typeof AdminProductsImportsRouteWithChildren
  '/admin/products/stock': typeof AdminProductsStockRouteWithChildren
  '/admin/security/mfa': typeof AdminSecurityMfaRoute
  '/admin/version-updates/$id': typeof AdminVersionUpdatesIdRoute
  '/admin/version-updates/new': typeof AdminVersionUpdatesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cms-media/$id': typeof ApiCmsMediaIdRoute
  '/api/internal/stock-sync': typeof ApiInternalStockSyncRoute
  '/api/product-documents/$id': typeof ApiProductDocumentsIdRoute
  '/portal/orders/$orderId': typeof PortalOrdersOrderIdRouteWithChildren
  '/portal/quotes/$quoteId': typeof PortalQuotesQuoteIdRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
  '/purchasing/forecast/$sku': typeof PurchasingForecastSkuRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/quotes/$quoteId': typeof SalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/sales/sales-intelligence/daily-brief': typeof SalesSalesIntelligenceDailyBriefRoute
  '/sales/sales-intelligence/gaps': typeof SalesSalesIntelligenceGapsRoute
  '/sales/sales-intelligence/opportunities': typeof SalesSalesIntelligenceOpportunitiesRoute
  '/sales/sales-intelligence/portfolio': typeof SalesSalesIntelligencePortfolioRoute
  '/sales/sales-intelligence/rebates': typeof SalesSalesIntelligenceRebatesRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pricing/': typeof AdminPricingIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/version-updates/': typeof AdminVersionUpdatesIndexRoute
  '/portal/orders/': typeof PortalOrdersIndexRoute
  '/portal/quotes/': typeof PortalQuotesIndexRoute
  '/purchasing/forecast/': typeof PurchasingForecastIndexRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/quotes/': typeof SalesQuotesIndexRoute
  '/sales/sales-intelligence/': typeof SalesSalesIntelligenceIndexRoute
  '/admin/content/$slug/preview': typeof AdminContentSlugPreviewRoute
  '/admin/customers/groups/$groupId': typeof AdminCustomersGroupsGroupIdRoute
  '/admin/products/imports/$id': typeof AdminProductsImportsIdRoute
  '/portal/orders/$orderId/confirmation': typeof PortalOrdersOrderIdConfirmationRoute
  '/admin/customers/groups/': typeof AdminCustomersGroupsIndexRoute
  '/admin/products/imports/': typeof AdminProductsImportsIndexRoute
  '/portal/orders/$orderId/': typeof PortalOrdersOrderIdIndexRoute
  '/admin/products/stock/product/$sku': typeof AdminProductsStockProductSkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activate'
    | '/admin'
    | '/contact'
    | '/crm'
    | '/forgot-password'
    | '/login'
    | '/meet-the-team'
    | '/motorsport'
    | '/portal'
    | '/purchasing'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sales'
    | '/trade-solutions'
    | '/why-automotive-brands'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/cost-intelligence'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/version-updates'
    | '/api/build'
    | '/brands/$slug'
    | '/crm/activities'
    | '/crm/applications'
    | '/crm/leads'
    | '/crm/manager'
    | '/crm/overview'
    | '/crm/tasks'
    | '/portal/basket'
    | '/portal/checkout'
    | '/portal/favourites'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/purchases'
    | '/portal/quick-order'
    | '/portal/quotes'
    | '/portal/support'
    | '/portal/users'
    | '/products/$sku'
    | '/purchasing/forecast'
    | '/purchasing/overstock'
    | '/purchasing/planner'
    | '/sales/sales-intelligence'
    | '/admin/'
    | '/brands/'
    | '/crm/'
    | '/portal/'
    | '/products/'
    | '/purchasing/'
    | '/sales/'
    | '/admin/content/$slug'
    | '/admin/content/media'
    | '/admin/content/team'
    | '/admin/customers/$id'
    | '/admin/customers/autopart-accounts'
    | '/admin/orders/$orderId'
    | '/admin/pricing/$id'
    | '/admin/products/$id'
    | '/admin/products/documents'
    | '/admin/products/documents-import'
    | '/admin/products/imports'
    | '/admin/products/stock'
    | '/admin/security/mfa'
    | '/admin/version-updates/$id'
    | '/admin/version-updates/new'
    | '/api/auth/$'
    | '/api/cms-media/$id'
    | '/api/internal/stock-sync'
    | '/api/product-documents/$id'
    | '/portal/orders/$orderId'
    | '/portal/quotes/$quoteId'
    | '/products/category/$slug'
    | '/purchasing/forecast/$sku'
    | '/sales/customers/$id'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/sales/sales-intelligence/daily-brief'
    | '/sales/sales-intelligence/gaps'
    | '/sales/sales-intelligence/opportunities'
    | '/sales/sales-intelligence/portfolio'
    | '/sales/sales-intelligence/rebates'
    | '/admin/applications/'
    | '/admin/content/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/pricing/'
    | '/admin/products/'
    | '/admin/version-updates/'
    | '/portal/orders/'
    | '/portal/quotes/'
    | '/purchasing/forecast/'
    | '/sales/customers/'
    | '/sales/quotes/'
    | '/sales/sales-intelligence/'
    | '/admin/content/$slug/preview'
    | '/admin/customers/groups/$groupId'
    | '/admin/products/imports/$id'
    | '/portal/orders/$orderId/confirmation'
    | '/admin/customers/groups/'
    | '/admin/products/imports/'
    | '/portal/orders/$orderId/'
    | '/admin/products/stock/product/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activate'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/meet-the-team'
    | '/motorsport'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/trade-solutions'
    | '/why-automotive-brands'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/cost-intelligence'
    | '/admin/roles'
    | '/admin/settings'
    | '/api/build'
    | '/brands/$slug'
    | '/crm/activities'
    | '/crm/applications'
    | '/crm/leads'
    | '/crm/manager'
    | '/crm/overview'
    | '/crm/tasks'
    | '/portal/basket'
    | '/portal/checkout'
    | '/portal/favourites'
    | '/portal/invoices'
    | '/portal/purchases'
    | '/portal/quick-order'
    | '/portal/support'
    | '/portal/users'
    | '/products/$sku'
    | '/purchasing/overstock'
    | '/purchasing/planner'
    | '/admin'
    | '/brands'
    | '/crm'
    | '/portal'
    | '/products'
    | '/purchasing'
    | '/sales'
    | '/admin/content/$slug'
    | '/admin/content/media'
    | '/admin/content/team'
    | '/admin/customers/$id'
    | '/admin/customers/autopart-accounts'
    | '/admin/orders/$orderId'
    | '/admin/pricing/$id'
    | '/admin/products/$id'
    | '/admin/products/documents'
    | '/admin/products/documents-import'
    | '/admin/products/stock'
    | '/admin/security/mfa'
    | '/admin/version-updates/$id'
    | '/admin/version-updates/new'
    | '/api/auth/$'
    | '/api/cms-media/$id'
    | '/api/internal/stock-sync'
    | '/api/product-documents/$id'
    | '/portal/quotes/$quoteId'
    | '/products/category/$slug'
    | '/purchasing/forecast/$sku'
    | '/sales/customers/$id'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/sales/sales-intelligence/daily-brief'
    | '/sales/sales-intelligence/gaps'
    | '/sales/sales-intelligence/opportunities'
    | '/sales/sales-intelligence/portfolio'
    | '/sales/sales-intelligence/rebates'
    | '/admin/applications'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/version-updates'
    | '/portal/orders'
    | '/portal/quotes'
    | '/purchasing/forecast'
    | '/sales/customers'
    | '/sales/quotes'
    | '/sales/sales-intelligence'
    | '/admin/content/$slug/preview'
    | '/admin/customers/groups/$groupId'
    | '/admin/products/imports/$id'
    | '/portal/orders/$orderId/confirmation'
    | '/admin/customers/groups'
    | '/admin/products/imports'
    | '/portal/orders/$orderId'
    | '/admin/products/stock/product/$sku'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activate'
    | '/admin'
    | '/contact'
    | '/crm'
    | '/forgot-password'
    | '/login'
    | '/meet-the-team'
    | '/motorsport'
    | '/portal'
    | '/purchasing'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sales'
    | '/trade-solutions'
    | '/why-automotive-brands'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/cost-intelligence'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/version-updates'
    | '/api/build'
    | '/brands/$slug'
    | '/crm/activities'
    | '/crm/applications'
    | '/crm/leads'
    | '/crm/manager'
    | '/crm/overview'
    | '/crm/tasks'
    | '/portal/basket'
    | '/portal/checkout'
    | '/portal/favourites'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/purchases'
    | '/portal/quick-order'
    | '/portal/quotes'
    | '/portal/support'
    | '/portal/users'
    | '/products/$sku'
    | '/purchasing/forecast'
    | '/purchasing/overstock'
    | '/purchasing/planner'
    | '/sales/sales-intelligence'
    | '/admin/'
    | '/brands/'
    | '/crm/'
    | '/portal/'
    | '/products/'
    | '/purchasing/'
    | '/sales/'
    | '/admin/content/$slug'
    | '/admin/content/media'
    | '/admin/content/team'
    | '/admin/customers/$id'
    | '/admin/customers/autopart-accounts'
    | '/admin/orders/$orderId'
    | '/admin/pricing/$id'
    | '/admin/products/$id'
    | '/admin/products/documents'
    | '/admin/products/documents-import'
    | '/admin/products/imports'
    | '/admin/products/stock'
    | '/admin/security/mfa'
    | '/admin/version-updates/$id'
    | '/admin/version-updates/new'
    | '/api/auth/$'
    | '/api/cms-media/$id'
    | '/api/internal/stock-sync'
    | '/api/product-documents/$id'
    | '/portal/orders/$orderId'
    | '/portal/quotes/$quoteId'
    | '/products/category/$slug'
    | '/purchasing/forecast/$sku'
    | '/sales/customers/$id'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/sales/sales-intelligence/daily-brief'
    | '/sales/sales-intelligence/gaps'
    | '/sales/sales-intelligence/opportunities'
    | '/sales/sales-intelligence/portfolio'
    | '/sales/sales-intelligence/rebates'
    | '/admin/applications/'
    | '/admin/content/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/pricing/'
    | '/admin/products/'
    | '/admin/version-updates/'
    | '/portal/orders/'
    | '/portal/quotes/'
    | '/purchasing/forecast/'
    | '/sales/customers/'
    | '/sales/quotes/'
    | '/sales/sales-intelligence/'
    | '/admin/content/$slug/preview'
    | '/admin/customers/groups/$groupId'
    | '/admin/products/imports/$id'
    | '/portal/orders/$orderId/confirmation'
    | '/admin/customers/groups/'
    | '/admin/products/imports/'
    | '/portal/orders/$orderId/'
    | '/admin/products/stock/product/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MeetTheTeamRoute: typeof MeetTheTeamRoute
  MotorsportRoute: typeof MotorsportRoute
  PortalRoute: typeof PortalRouteWithChildren
  PurchasingRoute: typeof PurchasingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SalesRoute: typeof SalesRouteWithChildren
  TradeSolutionsRoute: typeof TradeSolutionsRoute
  WhyAutomotiveBrandsRoute: typeof WhyAutomotiveBrandsRoute
  ApiBuildRoute: typeof ApiBuildRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  ProductsSkuRoute: typeof ProductsSkuRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCmsMediaIdRoute: typeof ApiCmsMediaIdRoute
  ApiInternalStockSyncRoute: typeof ApiInternalStockSyncRoute
  ApiProductDocumentsIdRoute: typeof ApiProductDocumentsIdRoute
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-team': {
      id: '/meet-the-team'
      path: '/meet-the-team'
      fullPath: '/meet-the-team'
      preLoaderRoute: typeof MeetTheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorsport': {
      id: '/motorsport'
      path: '/motorsport'
      fullPath: '/motorsport'
      preLoaderRoute: typeof MotorsportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-solutions': {
      id: '/trade-solutions'
      path: '/trade-solutions'
      fullPath: '/trade-solutions'
      preLoaderRoute: typeof TradeSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-automotive-brands': {
      id: '/why-automotive-brands'
      path: '/why-automotive-brands'
      fullPath: '/why-automotive-brands'
      preLoaderRoute: typeof WhyAutomotiveBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cost-intelligence': {
      id: '/admin/cost-intelligence'
      path: '/cost-intelligence'
      fullPath: '/admin/cost-intelligence'
      preLoaderRoute: typeof AdminCostIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/version-updates': {
      id: '/admin/version-updates'
      path: '/version-updates'
      fullPath: '/admin/version-updates'
      preLoaderRoute: typeof AdminVersionUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/build': {
      id: '/api/build'
      path: '/api/build'
      fullPath: '/api/build'
      preLoaderRoute: typeof ApiBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/activities': {
      id: '/crm/activities'
      path: '/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof CrmActivitiesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/applications': {
      id: '/crm/applications'
      path: '/applications'
      fullPath: '/crm/applications'
      preLoaderRoute: typeof CrmApplicationsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/manager': {
      id: '/crm/manager'
      path: '/manager'
      fullPath: '/crm/manager'
      preLoaderRoute: typeof CrmManagerRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/overview': {
      id: '/crm/overview'
      path: '/overview'
      fullPath: '/crm/overview'
      preLoaderRoute: typeof CrmOverviewRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/basket': {
      id: '/portal/basket'
      path: '/basket'
      fullPath: '/portal/basket'
      preLoaderRoute: typeof PortalBasketRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/checkout': {
      id: '/portal/checkout'
      path: '/checkout'
      fullPath: '/portal/checkout'
      preLoaderRoute: typeof PortalCheckoutRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/favourites': {
      id: '/portal/favourites'
      path: '/favourites'
      fullPath: '/portal/favourites'
      preLoaderRoute: typeof PortalFavouritesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/purchases': {
      id: '/portal/purchases'
      path: '/purchases'
      fullPath: '/portal/purchases'
      preLoaderRoute: typeof PortalPurchasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quick-order': {
      id: '/portal/quick-order'
      path: '/quick-order'
      fullPath: '/portal/quick-order'
      preLoaderRoute: typeof PortalQuickOrderRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quotes': {
      id: '/portal/quotes'
      path: '/quotes'
      fullPath: '/portal/quotes'
      preLoaderRoute: typeof PortalQuotesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/users': {
      id: '/portal/users'
      path: '/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof PortalUsersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$sku': {
      id: '/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof ProductsSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing/': {
      id: '/purchasing/'
      path: '/'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof PurchasingIndexRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/purchasing/forecast': {
      id: '/purchasing/forecast'
      path: '/forecast'
      fullPath: '/purchasing/forecast'
      preLoaderRoute: typeof PurchasingForecastRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/purchasing/overstock': {
      id: '/purchasing/overstock'
      path: '/overstock'
      fullPath: '/purchasing/overstock'
      preLoaderRoute: typeof PurchasingOverstockRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/purchasing/planner': {
      id: '/purchasing/planner'
      path: '/planner'
      fullPath: '/purchasing/planner'
      preLoaderRoute: typeof PurchasingPlannerRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/sales-intelligence': {
      id: '/sales/sales-intelligence'
      path: '/sales-intelligence'
      fullPath: '/sales/sales-intelligence'
      preLoaderRoute: typeof SalesSalesIntelligenceRouteImport
      parentRoute: typeof SalesRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/$slug': {
      id: '/admin/content/$slug'
      path: '/$slug'
      fullPath: '/admin/content/$slug'
      preLoaderRoute: typeof AdminContentSlugRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/media': {
      id: '/admin/content/media'
      path: '/media'
      fullPath: '/admin/content/media'
      preLoaderRoute: typeof AdminContentMediaRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/team': {
      id: '/admin/content/team'
      path: '/team'
      fullPath: '/admin/content/team'
      preLoaderRoute: typeof AdminContentTeamRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/autopart-accounts': {
      id: '/admin/customers/autopart-accounts'
      path: '/customers/autopart-accounts'
      fullPath: '/admin/customers/autopart-accounts'
      preLoaderRoute: typeof AdminCustomersAutopartAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/pricing/': {
      id: '/admin/pricing/'
      path: '/'
      fullPath: '/admin/pricing/'
      preLoaderRoute: typeof AdminPricingIndexRouteImport
      parentRoute: typeof AdminPricingRoute
    }
    '/admin/pricing/$id': {
      id: '/admin/pricing/$id'
      path: '/$id'
      fullPath: '/admin/pricing/$id'
      preLoaderRoute: typeof AdminPricingIdRouteImport
      parentRoute: typeof AdminPricingRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/documents': {
      id: '/admin/products/documents'
      path: '/documents'
      fullPath: '/admin/products/documents'
      preLoaderRoute: typeof AdminProductsDocumentsRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/documents-import': {
      id: '/admin/products/documents-import'
      path: '/documents-import'
      fullPath: '/admin/products/documents-import'
      preLoaderRoute: typeof AdminProductsDocumentsImportRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/imports': {
      id: '/admin/products/imports'
      path: '/imports'
      fullPath: '/admin/products/imports'
      preLoaderRoute: typeof AdminProductsImportsRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/stock': {
      id: '/admin/products/stock'
      path: '/stock'
      fullPath: '/admin/products/stock'
      preLoaderRoute: typeof AdminProductsStockRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/security/mfa': {
      id: '/admin/security/mfa'
      path: '/security/mfa'
      fullPath: '/admin/security/mfa'
      preLoaderRoute: typeof AdminSecurityMfaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/version-updates/': {
      id: '/admin/version-updates/'
      path: '/'
      fullPath: '/admin/version-updates/'
      preLoaderRoute: typeof AdminVersionUpdatesIndexRouteImport
      parentRoute: typeof AdminVersionUpdatesRoute
    }
    '/admin/version-updates/$id': {
      id: '/admin/version-updates/$id'
      path: '/$id'
      fullPath: '/admin/version-updates/$id'
      preLoaderRoute: typeof AdminVersionUpdatesIdRouteImport
      parentRoute: typeof AdminVersionUpdatesRoute
    }
    '/admin/version-updates/new': {
      id: '/admin/version-updates/new'
      path: '/new'
      fullPath: '/admin/version-updates/new'
      preLoaderRoute: typeof AdminVersionUpdatesNewRouteImport
      parentRoute: typeof AdminVersionUpdatesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms-media/$id': {
      id: '/api/cms-media/$id'
      path: '/api/cms-media/$id'
      fullPath: '/api/cms-media/$id'
      preLoaderRoute: typeof ApiCmsMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/stock-sync': {
      id: '/api/internal/stock-sync'
      path: '/api/internal/stock-sync'
      fullPath: '/api/internal/stock-sync'
      preLoaderRoute: typeof ApiInternalStockSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-documents/$id': {
      id: '/api/product-documents/$id'
      path: '/api/product-documents/$id'
      fullPath: '/api/product-documents/$id'
      preLoaderRoute: typeof ApiProductDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/orders/': {
      id: '/portal/orders/'
      path: '/'
      fullPath: '/portal/orders/'
      preLoaderRoute: typeof PortalOrdersIndexRouteImport
      parentRoute: typeof PortalOrdersRoute
    }
    '/portal/orders/$orderId': {
      id: '/portal/orders/$orderId'
      path: '/$orderId'
      fullPath: '/portal/orders/$orderId'
      preLoaderRoute: typeof PortalOrdersOrderIdRouteImport
      parentRoute: typeof PortalOrdersRoute
    }
    '/portal/quotes/': {
      id: '/portal/quotes/'
      path: '/'
      fullPath: '/portal/quotes/'
      preLoaderRoute: typeof PortalQuotesIndexRouteImport
      parentRoute: typeof PortalQuotesRoute
    }
    '/portal/quotes/$quoteId': {
      id: '/portal/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/portal/quotes/$quoteId'
      preLoaderRoute: typeof PortalQuotesQuoteIdRouteImport
      parentRoute: typeof PortalQuotesRoute
    }
    '/products/category/$slug': {
      id: '/products/category/$slug'
      path: '/products/category/$slug'
      fullPath: '/products/category/$slug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing/forecast/': {
      id: '/purchasing/forecast/'
      path: '/'
      fullPath: '/purchasing/forecast/'
      preLoaderRoute: typeof PurchasingForecastIndexRouteImport
      parentRoute: typeof PurchasingForecastRoute
    }
    '/purchasing/forecast/$sku': {
      id: '/purchasing/forecast/$sku'
      path: '/$sku'
      fullPath: '/purchasing/forecast/$sku'
      preLoaderRoute: typeof PurchasingForecastSkuRouteImport
      parentRoute: typeof PurchasingForecastRoute
    }
    '/sales/customers/': {
      id: '/sales/customers/'
      path: '/customers'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof SalesCustomersIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/customers/$id': {
      id: '/sales/customers/$id'
      path: '/customers/$id'
      fullPath: '/sales/customers/$id'
      preLoaderRoute: typeof SalesCustomersIdRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/quotes/': {
      id: '/sales/quotes/'
      path: '/quotes'
      fullPath: '/sales/quotes/'
      preLoaderRoute: typeof SalesQuotesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/quotes/$quoteId': {
      id: '/sales/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/sales/quotes/$quoteId'
      preLoaderRoute: typeof SalesQuotesQuoteIdRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/quotes/new': {
      id: '/sales/quotes/new'
      path: '/quotes/new'
      fullPath: '/sales/quotes/new'
      preLoaderRoute: typeof SalesQuotesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/sales-intelligence/': {
      id: '/sales/sales-intelligence/'
      path: '/'
      fullPath: '/sales/sales-intelligence/'
      preLoaderRoute: typeof SalesSalesIntelligenceIndexRouteImport
      parentRoute: typeof SalesSalesIntelligenceRoute
    }
    '/sales/sales-intelligence/daily-brief': {
      id: '/sales/sales-intelligence/daily-brief'
      path: '/daily-brief'
      fullPath: '/sales/sales-intelligence/daily-brief'
      preLoaderRoute: typeof SalesSalesIntelligenceDailyBriefRouteImport
      parentRoute: typeof SalesSalesIntelligenceRoute
    }
    '/sales/sales-intelligence/gaps': {
      id: '/sales/sales-intelligence/gaps'
      path: '/gaps'
      fullPath: '/sales/sales-intelligence/gaps'
      preLoaderRoute: typeof SalesSalesIntelligenceGapsRouteImport
      parentRoute: typeof SalesSalesIntelligenceRoute
    }
    '/sales/sales-intelligence/opportunities': {
      id: '/sales/sales-intelligence/opportunities'
      path: '/opportunities'
      fullPath: '/sales/sales-intelligence/opportunities'
      preLoaderRoute: typeof SalesSalesIntelligenceOpportunitiesRouteImport
      parentRoute: typeof SalesSalesIntelligenceRoute
    }
    '/sales/sales-intelligence/portfolio': {
      id: '/sales/sales-intelligence/portfolio'
      path: '/portfolio'
      fullPath: '/sales/sales-intelligence/portfolio'
      preLoaderRoute: typeof SalesSalesIntelligencePortfolioRouteImport
      parentRoute: typeof SalesSalesIntelligenceRoute
    }
    '/sales/sales-intelligence/rebates': {
      id: '/sales/sales-intelligence/rebates'
      path: '/rebates'
      fullPath: '/sales/sales-intelligence/rebates'
      preLoaderRoute: typeof SalesSalesIntelligenceRebatesRouteImport
      parentRoute: typeof SalesSalesIntelligenceRoute
    }
    '/admin/content/$slug/preview': {
      id: '/admin/content/$slug/preview'
      path: '/preview'
      fullPath: '/admin/content/$slug/preview'
      preLoaderRoute: typeof AdminContentSlugPreviewRouteImport
      parentRoute: typeof AdminContentSlugRoute
    }
    '/admin/customers/groups/': {
      id: '/admin/customers/groups/'
      path: '/customers/groups'
      fullPath: '/admin/customers/groups/'
      preLoaderRoute: typeof AdminCustomersGroupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/groups/$groupId': {
      id: '/admin/customers/groups/$groupId'
      path: '/customers/groups/$groupId'
      fullPath: '/admin/customers/groups/$groupId'
      preLoaderRoute: typeof AdminCustomersGroupsGroupIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/imports/': {
      id: '/admin/products/imports/'
      path: '/'
      fullPath: '/admin/products/imports/'
      preLoaderRoute: typeof AdminProductsImportsIndexRouteImport
      parentRoute: typeof AdminProductsImportsRoute
    }
    '/admin/products/imports/$id': {
      id: '/admin/products/imports/$id'
      path: '/$id'
      fullPath: '/admin/products/imports/$id'
      preLoaderRoute: typeof AdminProductsImportsIdRouteImport
      parentRoute: typeof AdminProductsImportsRoute
    }
    '/portal/orders/$orderId/': {
      id: '/portal/orders/$orderId/'
      path: '/'
      fullPath: '/portal/orders/$orderId/'
      preLoaderRoute: typeof PortalOrdersOrderIdIndexRouteImport
      parentRoute: typeof PortalOrdersOrderIdRoute
    }
    '/portal/orders/$orderId/confirmation': {
      id: '/portal/orders/$orderId/confirmation'
      path: '/confirmation'
      fullPath: '/portal/orders/$orderId/confirmation'
      preLoaderRoute: typeof PortalOrdersOrderIdConfirmationRouteImport
      parentRoute: typeof PortalOrdersOrderIdRoute
    }
    '/admin/products/stock/product/$sku': {
      id: '/admin/products/stock/product/$sku'
      path: '/product/$sku'
      fullPath: '/admin/products/stock/product/$sku'
      preLoaderRoute: typeof AdminProductsStockProductSkuRouteImport
      parentRoute: typeof AdminProductsStockRoute
    }
  }
}

interface AdminContentSlugRouteChildren {
  AdminContentSlugPreviewRoute: typeof AdminContentSlugPreviewRoute
}

const AdminContentSlugRouteChildren: AdminContentSlugRouteChildren = {
  AdminContentSlugPreviewRoute: AdminContentSlugPreviewRoute,
}

const AdminContentSlugRouteWithChildren =
  AdminContentSlugRoute._addFileChildren(AdminContentSlugRouteChildren)

interface AdminContentRouteChildren {
  AdminContentSlugRoute: typeof AdminContentSlugRouteWithChildren
  AdminContentMediaRoute: typeof AdminContentMediaRoute
  AdminContentTeamRoute: typeof AdminContentTeamRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentSlugRoute: AdminContentSlugRouteWithChildren,
  AdminContentMediaRoute: AdminContentMediaRoute,
  AdminContentTeamRoute: AdminContentTeamRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminPricingRouteChildren {
  AdminPricingIdRoute: typeof AdminPricingIdRoute
  AdminPricingIndexRoute: typeof AdminPricingIndexRoute
}

const AdminPricingRouteChildren: AdminPricingRouteChildren = {
  AdminPricingIdRoute: AdminPricingIdRoute,
  AdminPricingIndexRoute: AdminPricingIndexRoute,
}

const AdminPricingRouteWithChildren = AdminPricingRoute._addFileChildren(
  AdminPricingRouteChildren,
)

interface AdminProductsImportsRouteChildren {
  AdminProductsImportsIdRoute: typeof AdminProductsImportsIdRoute
  AdminProductsImportsIndexRoute: typeof AdminProductsImportsIndexRoute
}

const AdminProductsImportsRouteChildren: AdminProductsImportsRouteChildren = {
  AdminProductsImportsIdRoute: AdminProductsImportsIdRoute,
  AdminProductsImportsIndexRoute: AdminProductsImportsIndexRoute,
}

const AdminProductsImportsRouteWithChildren =
  AdminProductsImportsRoute._addFileChildren(AdminProductsImportsRouteChildren)

interface AdminProductsStockRouteChildren {
  AdminProductsStockProductSkuRoute: typeof AdminProductsStockProductSkuRoute
}

const AdminProductsStockRouteChildren: AdminProductsStockRouteChildren = {
  AdminProductsStockProductSkuRoute: AdminProductsStockProductSkuRoute,
}

const AdminProductsStockRouteWithChildren =
  AdminProductsStockRoute._addFileChildren(AdminProductsStockRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsDocumentsRoute: typeof AdminProductsDocumentsRoute
  AdminProductsDocumentsImportRoute: typeof AdminProductsDocumentsImportRoute
  AdminProductsImportsRoute: typeof AdminProductsImportsRouteWithChildren
  AdminProductsStockRoute: typeof AdminProductsStockRouteWithChildren
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsDocumentsRoute: AdminProductsDocumentsRoute,
  AdminProductsDocumentsImportRoute: AdminProductsDocumentsImportRoute,
  AdminProductsImportsRoute: AdminProductsImportsRouteWithChildren,
  AdminProductsStockRoute: AdminProductsStockRouteWithChildren,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminVersionUpdatesRouteChildren {
  AdminVersionUpdatesIdRoute: typeof AdminVersionUpdatesIdRoute
  AdminVersionUpdatesNewRoute: typeof AdminVersionUpdatesNewRoute
  AdminVersionUpdatesIndexRoute: typeof AdminVersionUpdatesIndexRoute
}

const AdminVersionUpdatesRouteChildren: AdminVersionUpdatesRouteChildren = {
  AdminVersionUpdatesIdRoute: AdminVersionUpdatesIdRoute,
  AdminVersionUpdatesNewRoute: AdminVersionUpdatesNewRoute,
  AdminVersionUpdatesIndexRoute: AdminVersionUpdatesIndexRoute,
}

const AdminVersionUpdatesRouteWithChildren =
  AdminVersionUpdatesRoute._addFileChildren(AdminVersionUpdatesRouteChildren)

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminCostIntelligenceRoute: typeof AdminCostIntelligenceRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPricingRoute: typeof AdminPricingRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVersionUpdatesRoute: typeof AdminVersionUpdatesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminCustomersAutopartAccountsRoute: typeof AdminCustomersAutopartAccountsRoute
  AdminSecurityMfaRoute: typeof AdminSecurityMfaRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminCustomersGroupsGroupIdRoute: typeof AdminCustomersGroupsGroupIdRoute
  AdminCustomersGroupsIndexRoute: typeof AdminCustomersGroupsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminCostIntelligenceRoute: AdminCostIntelligenceRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPricingRoute: AdminPricingRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVersionUpdatesRoute: AdminVersionUpdatesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminCustomersAutopartAccountsRoute: AdminCustomersAutopartAccountsRoute,
  AdminSecurityMfaRoute: AdminSecurityMfaRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminCustomersGroupsGroupIdRoute: AdminCustomersGroupsGroupIdRoute,
  AdminCustomersGroupsIndexRoute: AdminCustomersGroupsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CrmRouteChildren {
  CrmActivitiesRoute: typeof CrmActivitiesRoute
  CrmApplicationsRoute: typeof CrmApplicationsRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmManagerRoute: typeof CrmManagerRoute
  CrmOverviewRoute: typeof CrmOverviewRoute
  CrmTasksRoute: typeof CrmTasksRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmActivitiesRoute: CrmActivitiesRoute,
  CrmApplicationsRoute: CrmApplicationsRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmManagerRoute: CrmManagerRoute,
  CrmOverviewRoute: CrmOverviewRoute,
  CrmTasksRoute: CrmTasksRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface PortalOrdersOrderIdRouteChildren {
  PortalOrdersOrderIdConfirmationRoute: typeof PortalOrdersOrderIdConfirmationRoute
  PortalOrdersOrderIdIndexRoute: typeof PortalOrdersOrderIdIndexRoute
}

const PortalOrdersOrderIdRouteChildren: PortalOrdersOrderIdRouteChildren = {
  PortalOrdersOrderIdConfirmationRoute: PortalOrdersOrderIdConfirmationRoute,
  PortalOrdersOrderIdIndexRoute: PortalOrdersOrderIdIndexRoute,
}

const PortalOrdersOrderIdRouteWithChildren =
  PortalOrdersOrderIdRoute._addFileChildren(PortalOrdersOrderIdRouteChildren)

interface PortalOrdersRouteChildren {
  PortalOrdersOrderIdRoute: typeof PortalOrdersOrderIdRouteWithChildren
  PortalOrdersIndexRoute: typeof PortalOrdersIndexRoute
}

const PortalOrdersRouteChildren: PortalOrdersRouteChildren = {
  PortalOrdersOrderIdRoute: PortalOrdersOrderIdRouteWithChildren,
  PortalOrdersIndexRoute: PortalOrdersIndexRoute,
}

const PortalOrdersRouteWithChildren = PortalOrdersRoute._addFileChildren(
  PortalOrdersRouteChildren,
)

interface PortalQuotesRouteChildren {
  PortalQuotesQuoteIdRoute: typeof PortalQuotesQuoteIdRoute
  PortalQuotesIndexRoute: typeof PortalQuotesIndexRoute
}

const PortalQuotesRouteChildren: PortalQuotesRouteChildren = {
  PortalQuotesQuoteIdRoute: PortalQuotesQuoteIdRoute,
  PortalQuotesIndexRoute: PortalQuotesIndexRoute,
}

const PortalQuotesRouteWithChildren = PortalQuotesRoute._addFileChildren(
  PortalQuotesRouteChildren,
)

interface PortalRouteChildren {
  PortalBasketRoute: typeof PortalBasketRoute
  PortalCheckoutRoute: typeof PortalCheckoutRoute
  PortalFavouritesRoute: typeof PortalFavouritesRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalOrdersRoute: typeof PortalOrdersRouteWithChildren
  PortalPurchasesRoute: typeof PortalPurchasesRoute
  PortalQuickOrderRoute: typeof PortalQuickOrderRoute
  PortalQuotesRoute: typeof PortalQuotesRouteWithChildren
  PortalSupportRoute: typeof PortalSupportRoute
  PortalUsersRoute: typeof PortalUsersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBasketRoute: PortalBasketRoute,
  PortalCheckoutRoute: PortalCheckoutRoute,
  PortalFavouritesRoute: PortalFavouritesRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalOrdersRoute: PortalOrdersRouteWithChildren,
  PortalPurchasesRoute: PortalPurchasesRoute,
  PortalQuickOrderRoute: PortalQuickOrderRoute,
  PortalQuotesRoute: PortalQuotesRouteWithChildren,
  PortalSupportRoute: PortalSupportRoute,
  PortalUsersRoute: PortalUsersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface PurchasingForecastRouteChildren {
  PurchasingForecastSkuRoute: typeof PurchasingForecastSkuRoute
  PurchasingForecastIndexRoute: typeof PurchasingForecastIndexRoute
}

const PurchasingForecastRouteChildren: PurchasingForecastRouteChildren = {
  PurchasingForecastSkuRoute: PurchasingForecastSkuRoute,
  PurchasingForecastIndexRoute: PurchasingForecastIndexRoute,
}

const PurchasingForecastRouteWithChildren =
  PurchasingForecastRoute._addFileChildren(PurchasingForecastRouteChildren)

interface PurchasingRouteChildren {
  PurchasingForecastRoute: typeof PurchasingForecastRouteWithChildren
  PurchasingOverstockRoute: typeof PurchasingOverstockRoute
  PurchasingPlannerRoute: typeof PurchasingPlannerRoute
  PurchasingIndexRoute: typeof PurchasingIndexRoute
}

const PurchasingRouteChildren: PurchasingRouteChildren = {
  PurchasingForecastRoute: PurchasingForecastRouteWithChildren,
  PurchasingOverstockRoute: PurchasingOverstockRoute,
  PurchasingPlannerRoute: PurchasingPlannerRoute,
  PurchasingIndexRoute: PurchasingIndexRoute,
}

const PurchasingRouteWithChildren = PurchasingRoute._addFileChildren(
  PurchasingRouteChildren,
)

interface SalesSalesIntelligenceRouteChildren {
  SalesSalesIntelligenceDailyBriefRoute: typeof SalesSalesIntelligenceDailyBriefRoute
  SalesSalesIntelligenceGapsRoute: typeof SalesSalesIntelligenceGapsRoute
  SalesSalesIntelligenceOpportunitiesRoute: typeof SalesSalesIntelligenceOpportunitiesRoute
  SalesSalesIntelligencePortfolioRoute: typeof SalesSalesIntelligencePortfolioRoute
  SalesSalesIntelligenceRebatesRoute: typeof SalesSalesIntelligenceRebatesRoute
  SalesSalesIntelligenceIndexRoute: typeof SalesSalesIntelligenceIndexRoute
}

const SalesSalesIntelligenceRouteChildren: SalesSalesIntelligenceRouteChildren =
  {
    SalesSalesIntelligenceDailyBriefRoute:
      SalesSalesIntelligenceDailyBriefRoute,
    SalesSalesIntelligenceGapsRoute: SalesSalesIntelligenceGapsRoute,
    SalesSalesIntelligenceOpportunitiesRoute:
      SalesSalesIntelligenceOpportunitiesRoute,
    SalesSalesIntelligencePortfolioRoute: SalesSalesIntelligencePortfolioRoute,
    SalesSalesIntelligenceRebatesRoute: SalesSalesIntelligenceRebatesRoute,
    SalesSalesIntelligenceIndexRoute: SalesSalesIntelligenceIndexRoute,
  }

const SalesSalesIntelligenceRouteWithChildren =
  SalesSalesIntelligenceRoute._addFileChildren(
    SalesSalesIntelligenceRouteChildren,
  )

interface SalesRouteChildren {
  SalesSalesIntelligenceRoute: typeof SalesSalesIntelligenceRouteWithChildren
  SalesIndexRoute: typeof SalesIndexRoute
  SalesCustomersIdRoute: typeof SalesCustomersIdRoute
  SalesQuotesQuoteIdRoute: typeof SalesQuotesQuoteIdRoute
  SalesQuotesNewRoute: typeof SalesQuotesNewRoute
  SalesCustomersIndexRoute: typeof SalesCustomersIndexRoute
  SalesQuotesIndexRoute: typeof SalesQuotesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesSalesIntelligenceRoute: SalesSalesIntelligenceRouteWithChildren,
  SalesIndexRoute: SalesIndexRoute,
  SalesCustomersIdRoute: SalesCustomersIdRoute,
  SalesQuotesQuoteIdRoute: SalesQuotesQuoteIdRoute,
  SalesQuotesNewRoute: SalesQuotesNewRoute,
  SalesCustomersIndexRoute: SalesCustomersIndexRoute,
  SalesQuotesIndexRoute: SalesQuotesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MeetTheTeamRoute: MeetTheTeamRoute,
  MotorsportRoute: MotorsportRoute,
  PortalRoute: PortalRouteWithChildren,
  PurchasingRoute: PurchasingRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SalesRoute: SalesRouteWithChildren,
  TradeSolutionsRoute: TradeSolutionsRoute,
  WhyAutomotiveBrandsRoute: WhyAutomotiveBrandsRoute,
  ApiBuildRoute: ApiBuildRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  ProductsSkuRoute: ProductsSkuRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCmsMediaIdRoute: ApiCmsMediaIdRoute,
  ApiInternalStockSyncRoute: ApiInternalStockSyncRoute,
  ApiProductDocumentsIdRoute: ApiProductDocumentsIdRoute,
  ProductsCategorySlugRoute: ProductsCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
