/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalQuickOrderRouteImport } from './routes/portal.quick-order'
import { Route as PortalUsersRouteImport } from './routes/portal.users'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSkuRouteImport } from './routes/products.$sku'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesCustomersIndexRouteImport } from './routes/sales.customers.index'
import { Route as SalesCustomersIdRouteImport } from './routes/sales.customers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuickOrderRoute = PortalQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUsersRoute = PortalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSkuRoute = ProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesCustomersIndexRoute = SalesCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesCustomersIdRoute = SalesCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => SalesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/sales': typeof SalesRouteWithChildren
  '/brands/$slug': typeof BrandsSlugRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/brands/': typeof BrandsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/brands': typeof BrandsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/customers': typeof SalesCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/sales': typeof SalesRouteWithChildren
  '/brands/$slug': typeof BrandsSlugRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/brands/': typeof BrandsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/register'
    | '/sales'
    | '/brands/$slug'
    | '/portal/orders'
    | '/portal/quick-order'
    | '/portal/users'
    | '/products/$sku'
    | '/brands/'
    | '/portal/'
    | '/products/'
    | '/sales/'
    | '/sales/customers/$id'
    | '/sales/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/brands/$slug'
    | '/portal/orders'
    | '/portal/quick-order'
    | '/portal/users'
    | '/products/$sku'
    | '/brands'
    | '/portal'
    | '/products'
    | '/sales'
    | '/sales/customers/$id'
    | '/sales/customers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/register'
    | '/sales'
    | '/brands/$slug'
    | '/portal/orders'
    | '/portal/quick-order'
    | '/portal/users'
    | '/products/$sku'
    | '/brands/'
    | '/portal/'
    | '/products/'
    | '/sales/'
    | '/sales/customers/$id'
    | '/sales/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SalesRoute: typeof SalesRouteWithChildren
  BrandsSlugRoute: typeof BrandsSlugRoute
  ProductsSkuRoute: typeof ProductsSkuRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quick-order': {
      id: '/portal/quick-order'
      path: '/quick-order'
      fullPath: '/portal/quick-order'
      preLoaderRoute: typeof PortalQuickOrderRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/users': {
      id: '/portal/users'
      path: '/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof PortalUsersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$sku': {
      id: '/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof ProductsSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/customers/': {
      id: '/sales/customers/'
      path: '/customers'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof SalesCustomersIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/customers/$id': {
      id: '/sales/customers/$id'
      path: '/customers/$id'
      fullPath: '/sales/customers/$id'
      preLoaderRoute: typeof SalesCustomersIdRouteImport
      parentRoute: typeof SalesRoute
    }
  }
}

interface PortalRouteChildren {
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalQuickOrderRoute: typeof PortalQuickOrderRoute
  PortalUsersRoute: typeof PortalUsersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalOrdersRoute: PortalOrdersRoute,
  PortalQuickOrderRoute: PortalQuickOrderRoute,
  PortalUsersRoute: PortalUsersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SalesRouteChildren {
  SalesIndexRoute: typeof SalesIndexRoute
  SalesCustomersIdRoute: typeof SalesCustomersIdRoute
  SalesCustomersIndexRoute: typeof SalesCustomersIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesIndexRoute: SalesIndexRoute,
  SalesCustomersIdRoute: SalesCustomersIdRoute,
  SalesCustomersIndexRoute: SalesCustomersIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SalesRoute: SalesRouteWithChildren,
  BrandsSlugRoute: BrandsSlugRoute,
  ProductsSkuRoute: ProductsSkuRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
