/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as TradeSolutionsRouteImport } from './routes/trade-solutions'
import { Route as WhyAutomotiveBrandsRouteImport } from './routes/why-automotive-brands'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmApplicationsRouteImport } from './routes/crm.applications'
import { Route as CrmManagerRouteImport } from './routes/crm.manager'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalFavouritesRouteImport } from './routes/portal.favourites'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalQuickOrderRouteImport } from './routes/portal.quick-order'
import { Route as PortalQuotesRouteImport } from './routes/portal.quotes'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalUsersRouteImport } from './routes/portal.users'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSkuRouteImport } from './routes/products.$sku'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SalesCustomersIndexRouteImport } from './routes/sales.customers.index'
import { Route as SalesCustomersIdRouteImport } from './routes/sales.customers.$id'
import { Route as SalesOrderIdRouteImport } from './routes/sales.order.$id'
import { Route as SalesQuotesIndexRouteImport } from './routes/sales.quotes.index'
import { Route as SalesQuotesNewRouteImport } from './routes/sales.quotes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSolutionsRoute = TradeSolutionsRouteImport.update({
  id: '/trade-solutions',
  path: '/trade-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyAutomotiveBrandsRoute = WhyAutomotiveBrandsRouteImport.update({
  id: '/why-automotive-brands',
  path: '/why-automotive-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmApplicationsRoute = CrmApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CrmRoute,
} as any)
const CrmManagerRoute = CrmManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => CrmRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFavouritesRoute = PortalFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuickOrderRoute = PortalQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuotesRoute = PortalQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUsersRoute = PortalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSkuRoute = ProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersIndexRoute = SalesCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesCustomersIdRoute = SalesCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => SalesRoute,
} as any)
const SalesOrderIdRoute = SalesOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => SalesRoute,
} as any)
const SalesQuotesIndexRoute = SalesQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesQuotesNewRoute = SalesQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => SalesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales': typeof SalesRouteWithChildren
  '/trade-solutions': typeof TradeSolutionsRoute
  '/why-automotive-brands': typeof WhyAutomotiveBrandsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/crm/applications': typeof CrmApplicationsRoute
  '/crm/manager': typeof CrmManagerRoute
  '/portal/favourites': typeof PortalFavouritesRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/quotes': typeof PortalQuotesRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/order/$id': typeof SalesOrderIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/quotes/': typeof SalesQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/trade-solutions': typeof TradeSolutionsRoute
  '/why-automotive-brands': typeof WhyAutomotiveBrandsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/crm/applications': typeof CrmApplicationsRoute
  '/crm/manager': typeof CrmManagerRoute
  '/portal/favourites': typeof PortalFavouritesRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/quotes': typeof PortalQuotesRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/admin': typeof AdminIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/crm': typeof CrmIndexRoute
  '/portal': typeof PortalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/order/$id': typeof SalesOrderIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/sales/customers': typeof SalesCustomersIndexRoute
  '/sales/quotes': typeof SalesQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales': typeof SalesRouteWithChildren
  '/trade-solutions': typeof TradeSolutionsRoute
  '/why-automotive-brands': typeof WhyAutomotiveBrandsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/crm/applications': typeof CrmApplicationsRoute
  '/crm/manager': typeof CrmManagerRoute
  '/portal/favourites': typeof PortalFavouritesRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/quick-order': typeof PortalQuickOrderRoute
  '/portal/quotes': typeof PortalQuotesRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/users': typeof PortalUsersRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/order/$id': typeof SalesOrderIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/quotes/': typeof SalesQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/crm'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sales'
    | '/trade-solutions'
    | '/why-automotive-brands'
    | '/admin/content'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/settings'
    | '/brands/$slug'
    | '/crm/applications'
    | '/crm/manager'
    | '/portal/favourites'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/quick-order'
    | '/portal/quotes'
    | '/portal/support'
    | '/portal/users'
    | '/products/$sku'
    | '/quote/$id'
    | '/admin/'
    | '/brands/'
    | '/crm/'
    | '/portal/'
    | '/products/'
    | '/sales/'
    | '/api/auth/$'
    | '/sales/customers/$id'
    | '/sales/order/$id'
    | '/sales/quotes/new'
    | '/sales/customers/'
    | '/sales/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/trade-solutions'
    | '/why-automotive-brands'
    | '/admin/content'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/settings'
    | '/brands/$slug'
    | '/crm/applications'
    | '/crm/manager'
    | '/portal/favourites'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/quick-order'
    | '/portal/quotes'
    | '/portal/support'
    | '/portal/users'
    | '/products/$sku'
    | '/quote/$id'
    | '/admin'
    | '/brands'
    | '/crm'
    | '/portal'
    | '/products'
    | '/sales'
    | '/api/auth/$'
    | '/sales/customers/$id'
    | '/sales/order/$id'
    | '/sales/quotes/new'
    | '/sales/customers'
    | '/sales/quotes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/crm'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sales'
    | '/trade-solutions'
    | '/why-automotive-brands'
    | '/admin/content'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/settings'
    | '/brands/$slug'
    | '/crm/applications'
    | '/crm/manager'
    | '/portal/favourites'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/quick-order'
    | '/portal/quotes'
    | '/portal/support'
    | '/portal/users'
    | '/products/$sku'
    | '/quote/$id'
    | '/admin/'
    | '/brands/'
    | '/crm/'
    | '/portal/'
    | '/products/'
    | '/sales/'
    | '/api/auth/$'
    | '/sales/customers/$id'
    | '/sales/order/$id'
    | '/sales/quotes/new'
    | '/sales/customers/'
    | '/sales/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SalesRoute: typeof SalesRouteWithChildren
  TradeSolutionsRoute: typeof TradeSolutionsRoute
  WhyAutomotiveBrandsRoute: typeof WhyAutomotiveBrandsRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  ProductsSkuRoute: typeof ProductsSkuRoute
  QuoteIdRoute: typeof QuoteIdRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-solutions': {
      id: '/trade-solutions'
      path: '/trade-solutions'
      fullPath: '/trade-solutions'
      preLoaderRoute: typeof TradeSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-automotive-brands': {
      id: '/why-automotive-brands'
      path: '/why-automotive-brands'
      fullPath: '/why-automotive-brands'
      preLoaderRoute: typeof WhyAutomotiveBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/applications': {
      id: '/crm/applications'
      path: '/applications'
      fullPath: '/crm/applications'
      preLoaderRoute: typeof CrmApplicationsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/manager': {
      id: '/crm/manager'
      path: '/manager'
      fullPath: '/crm/manager'
      preLoaderRoute: typeof CrmManagerRouteImport
      parentRoute: typeof CrmRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/favourites': {
      id: '/portal/favourites'
      path: '/favourites'
      fullPath: '/portal/favourites'
      preLoaderRoute: typeof PortalFavouritesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quick-order': {
      id: '/portal/quick-order'
      path: '/quick-order'
      fullPath: '/portal/quick-order'
      preLoaderRoute: typeof PortalQuickOrderRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quotes': {
      id: '/portal/quotes'
      path: '/quotes'
      fullPath: '/portal/quotes'
      preLoaderRoute: typeof PortalQuotesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/users': {
      id: '/portal/users'
      path: '/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof PortalUsersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$sku': {
      id: '/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof ProductsSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers/': {
      id: '/sales/customers/'
      path: '/customers'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof SalesCustomersIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/customers/$id': {
      id: '/sales/customers/$id'
      path: '/customers/$id'
      fullPath: '/sales/customers/$id'
      preLoaderRoute: typeof SalesCustomersIdRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/order/$id': {
      id: '/sales/order/$id'
      path: '/order/$id'
      fullPath: '/sales/order/$id'
      preLoaderRoute: typeof SalesOrderIdRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/quotes/': {
      id: '/sales/quotes/'
      path: '/quotes'
      fullPath: '/sales/quotes/'
      preLoaderRoute: typeof SalesQuotesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/quotes/new': {
      id: '/sales/quotes/new'
      path: '/quotes/new'
      fullPath: '/sales/quotes/new'
      preLoaderRoute: typeof SalesQuotesNewRouteImport
      parentRoute: typeof SalesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CrmRouteChildren {
  CrmApplicationsRoute: typeof CrmApplicationsRoute
  CrmManagerRoute: typeof CrmManagerRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmApplicationsRoute: CrmApplicationsRoute,
  CrmManagerRoute: CrmManagerRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface PortalRouteChildren {
  PortalFavouritesRoute: typeof PortalFavouritesRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalQuickOrderRoute: typeof PortalQuickOrderRoute
  PortalQuotesRoute: typeof PortalQuotesRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalUsersRoute: typeof PortalUsersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalFavouritesRoute: PortalFavouritesRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalQuickOrderRoute: PortalQuickOrderRoute,
  PortalQuotesRoute: PortalQuotesRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalUsersRoute: PortalUsersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SalesRouteChildren {
  SalesIndexRoute: typeof SalesIndexRoute
  SalesCustomersIdRoute: typeof SalesCustomersIdRoute
  SalesOrderIdRoute: typeof SalesOrderIdRoute
  SalesQuotesNewRoute: typeof SalesQuotesNewRoute
  SalesCustomersIndexRoute: typeof SalesCustomersIndexRoute
  SalesQuotesIndexRoute: typeof SalesQuotesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesIndexRoute: SalesIndexRoute,
  SalesCustomersIdRoute: SalesCustomersIdRoute,
  SalesOrderIdRoute: SalesOrderIdRoute,
  SalesQuotesNewRoute: SalesQuotesNewRoute,
  SalesCustomersIndexRoute: SalesCustomersIndexRoute,
  SalesQuotesIndexRoute: SalesQuotesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SalesRoute: SalesRouteWithChildren,
  TradeSolutionsRoute: TradeSolutionsRoute,
  WhyAutomotiveBrandsRoute: WhyAutomotiveBrandsRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  ProductsSkuRoute: ProductsSkuRoute,
  QuoteIdRoute: QuoteIdRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
